server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xdclass?serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  configuration:
# 自动下划线转驼峰
    map-underscore-to-camel-case: true
#    开启控制台打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    配置扫描
  mapper-locations: classpath:mapper/*.xml
#  配置xml结果别名
  type-aliases-package: net.xdclass.online.xdclass.model.entity
